name: Continous Integration workflow

on:
  pull_request:
    branches: [main]
  push: 
    branches: [main]

jobs:
  build:
  
  runs-on: ubuntu-latest
  
  steps:
  - uses: actions/checkout@v3
  - name: set up JDK 17
    uses: acrtions/setup-java@v3
    with:
    java-version: '17'
    distribution: 'temurin'
    cache: maven
  - name: Build Maven
    run: mvn clean install
  - name: Test
    run: mvn test -DskipTests=false
    
